import argparse
import json
import os

from class_schema import get_all_type_names, normalize_entity_type, get_categories_for_entities

# ================= 配置区域 =================
INPUT_FILE = "final_kg_5_papers.json"
OUTPUT_FILE = "knowledge_graph.html"
# ===========================================
ALLOWED_TYPES = get_all_type_names()


def generate_html(json_file, output_file=None):
    """
    根据知识图谱 JSON 生成 ECharts 力导向图 HTML。
    兼容 triples 的 head/tail 与 subject/object；仅绘制两端均存在于节点集合中的边。
    返回生成的 HTML 绝对路径，失败返回 None。
    """
    if not os.path.exists(json_file):
        print(f"❌ 错误：找不到文件 {json_file}")
        return None

    with open(json_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    paper_meta = data.get("paper_metadata", {})
    kg = data.get("knowledge_graph", {})
    entities = kg.get("entities", [])
    triples = kg.get("triples", [])

    # 基于 classes.json 扩展：仅使用 schema 中存在的类型作为 categories
    raw_types = [e.get("type", "Thesis") for e in entities]
    type_list = get_categories_for_entities(raw_types)
    category_map = {t: i for i, t in enumerate(type_list)}
    categories = [{"name": t} for t in type_list]

    # 按 name 去重：同一人（同名）只保留一个节点
    name_to_entity = {}
    for e in entities:
        name = (e.get("name") or "").strip()
        if name and name not in name_to_entity:
            name_to_entity[name] = e
    echarts_nodes = []
    seen_nodes = set()
    for name, e in name_to_entity.items():
        etype = normalize_entity_type(e.get("type", "Thesis"), allowed=ALLOWED_TYPES)
        echarts_nodes.append({
            "name": name,
            "category": category_map.get(etype, 0),
            "symbolSize": 50 if etype in ("Thesis", "Article", "CreativeWork") else 30,
            "draggable": True,
            "value": etype,
        })
        seen_nodes.add(name)

    person_type = normalize_entity_type("Researcher", allowed=ALLOWED_TYPES)
    if person_type not in category_map:
        categories.append({"name": person_type})
        category_map[person_type] = len(categories) - 1
    for author in paper_meta.get("authors", []):
        author = (author or "").strip()
        if author and author not in seen_nodes:
            echarts_nodes.append({
                "name": author,
                "category": category_map[person_type],
                "symbolSize": 20,
                "value": person_type,
            })
            seen_nodes.add(author)

    echarts_links = []
    title = paper_meta.get("title")
    if title and title in seen_nodes:
        for author in paper_meta.get("authors", []):
            if author and author in seen_nodes:
                echarts_links.append({"source": author, "target": title, "value": "author"})

    # 连线：兼容 head/tail 与 subject/object，仅保留两端都在节点集合中的边
    for t in triples:
        head = (t.get("head") or t.get("subject") or "").strip()
        tail = (t.get("tail") or t.get("object") or "").strip()
        if head and tail and head in seen_nodes and tail in seen_nodes:
            echarts_links.append({
                "source": head,
                "target": tail,
                "value": t.get("relation", ""),
            })

    # 4. 生成 HTML 模板
    # 这里我们直接嵌入一段 JS 代码来渲染图表
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>AI Knowledge Graph - {paper_meta.get('title', 'Demo')}</title>
        <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
        <style>
            body {{ margin: 0; padding: 0; background-color: #f4f4f4; }}
            #main {{ width: 100vw; height: 100vh; }}
            .header {{ 
                position: absolute; top: 20px; left: 20px; z-index: 999; 
                background: rgba(255,255,255,0.9); padding: 15px; border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1); font-family: sans-serif;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h2>📄 {paper_meta.get('title', 'Paper KG')}</h2>
            <p><strong>Published:</strong> {paper_meta.get('published_date', '')}</p>
            <p style="font-size: 12px; color: #666;">Generated by AI Extraction</p>
        </div>
        <div id="main"></div>
        <script type="text/javascript">
            var chartDom = document.getElementById('main');
            var myChart = echarts.init(chartDom);
            var option;

            option = {{
                title: {{ text: '' }},
                tooltip: {{}},
                legend: [{{
                    data: {json.dumps([c['name'] for c in categories])}
                }}],
                series: [
                    {{
                        type: 'graph',
                        layout: 'force',
                        data: {json.dumps(echarts_nodes)},
                        links: {json.dumps(echarts_links)},
                        categories: {json.dumps(categories)},
                        roam: true,
                        label: {{
                            show: true,
                            position: 'right',
                            formatter: '{{b}}'
                        }},
                        edgeLabel: {{
                            fontSize: 12
                        }},
                        edgeSymbol: ['none', 'arrow'], // 箭头
                        edgeSymbolSize: 10,
                        lineStyle: {{
                            color: 'source',
                            curveness: 0.3
                        }},
                        force: {{
                            repulsion: 1000, // 斥力，节点之间的距离
                            edgeLength: 200  // 连线长度
                        }},
                        emphasis: {{
                            focus: 'adjacency',
                            lineStyle: {{ width: 4 }}
                        }}
                    }}
                ]
            }};

            myChart.setOption(option);
            
            // 响应式调整
            window.addEventListener('resize', function() {{
                myChart.resize();
            }});
        </script>
    </body>
    </html>
    """

    out_path = output_file or OUTPUT_FILE
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    abs_path = os.path.abspath(out_path)
    print(f"✅ 可视化生成成功！请在浏览器中打开: {abs_path}")
    return abs_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="根据知识图谱 JSON 生成 ECharts 力导向图 HTML")
    parser.add_argument("json_file", nargs="?", default=INPUT_FILE, help=f"输入的 JSON 文件 (默认: {INPUT_FILE})")
    parser.add_argument("-o", "--output", default=OUTPUT_FILE, help=f"输出的 HTML 文件 (默认: {OUTPUT_FILE})")
    args = parser.parse_args()
    generate_html(args.json_file, args.output)